[package]
name = "swapi-sauvignon"
version = "0.1.0"
edition = "2024"

[dependencies]
sauvignon = { path = "../../sauvignon" }
sqlx = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_json_path = "0.7.2"
shared = { path = "../shared" }
