[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.5.53", features = ["derive"] }
jiff = { workspace = true, features = ["serde"] }
jiff-sqlx = { workspace = true }
regex = "1.12.2"
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = "3.16.1"
shared = { path = "../shared" }
sqlx = { workspace = true }
squalid = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
